#+TITLE: Introduction

In the early 20th century, the United States was undergoing great change. Roosevelt, who increased regulation and became known as the "trust-buster", retired after two terms, passing the presidency onto Taft. However, Taft was not following progressive trends and alienated much of the Republican party, leading to a four-way race in 1912. Wilson, a democrat with a reputation as a reformer, promised "New Freedom": the restoring of free competition and equal economic opportunity, whilst keeping federal control below the levels Roosevelt had wanted. Wilson won on this platform, and began making change - though more hesitantly than progressives wanted. By 1916, Wilson had reduced tariffs on materials and goods, instituted the first graduated income tax, created Federal Reserve Banks, and increased protections for labour unions and strikers.

However, the outbreak of World War I in Europe cut many of Wilson's plans short. Dealing with the war proved to be a challenging task, as the United States became a key supplier to the Allies despite a facade of neutrality. At the start of the war in 1914, the American public was overwhelmingly against participating in the conflict, but events such as the Rape of Belgium turned opinion of Germany low, and the sinking of the /RMS Lusitania/ led to increasing support for joining the Allies. Wilson himself was outraged. As Germany was prevented from receiving shipments by Britain, it no longer traded with the US, whilst trade with the Allies increased dramatically, almost quadrupling in value from 1914 to 1916. The United States was neutral only in name.

As Germany began submarine warfare in 1915, leading to the death and wounding of American civilians on ships from Allied countries, the administration began preparing for war, doubling the size of the regular army. Though Wilson had successfully campaigned for re-election in 1916 with the slogan "He Kept Us Out of War", Germany's 1917 declaration of unrestricted submarine warfare made it impossible to preserve the appearance of neutrality. In March, the White House intercepted the Zimmerman Note, an offer of alliance from Germany to Mexico in the event the US joined the Allies. That same month, German boats sunk seven American merchant ships, killing hundreds. The time had finally come for Wilson to make the case for war to Congress, which he did on 02 April, 1917. He signed a declaration of war four days later. The United States had entered the Great War.
